### PR TITLE
Metastore for Hive 3.1

### PR DESCRIPTION
**Pull request by kosinsky**
Added support for Hive 3.1 metastore

I based my PR on 2.3.0 branch, because master is still based on 2.10

Going to send another PR to docker-hive repo to add support for Hive 3.1.x (will fix https://github.com/big-data-europe/docker-hive/issues/26)

### CODE REVIEW

**Comment by earthquakesan** [comment]
lgtm

**Comment by kosinsky** [comment]
@earthquakesan, sorry, you merged it to 2.3.0 branch and republished image with 2.3.0 tag. However, it should be 3.1.0 branch on your side and as a result published image should have 3.1.0 tag. Could you fix that?

**Comment by earthquakesan** [comment]
@kosinsky I reverted the change, please make a pull request for the corresponding branch (new one)

**Comment by kosinsky** [comment]
https://github.com/big-data-europe/docker-hive-metastore-postgresql/pull/4 I don't have permissions to create 3.1.0 branch on your side. I'm pointing to master for now.

**Pull request merged**
